[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nereus"
version = "2.3.0"
description = "A Stone Soup plugin for underwater acoustic tracking."
readme = "README.md"
authors = [
    { name = "Joshua J Wakefield", email = "J.J.Wakefield@liverpool.ac.uk" },
    { name = "Fin Boulton", email = "F.Boulton@liverpool.ac.uk" },
]
license = { text = "MIT" }
keywords = ["nereus", "state estimation", "tracking", "sonar", "underwater-acoustics"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering",
]
dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "seaborn",
    "stonesoup",
    "numba",
    "rocket-fft",
    "tqdm",
]

[project.urls]
Repository = "https://github.com/jjwakefield/nereus"

[project.optional-dependencies]
dev = [
    "ruff",
    "pytest",
]
docs = [
    "sphinx",
    "sphinx-rtd-theme",
    "myst-parser",
    "myst-nb"
]
examples = [
    "ipykernel",
    "ipywidgets",
    "jupyterlab",
    "librosa"
]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["F", "E", "W", "I", "B", "D", "UP"]

[tool.setuptools.packages.find]
where = ["."]